const availableCountries = [
    "US",
    "AU",
    "BR",
    "CA",
    "CN",
    "FR",
    "DE",
    "IN",
    "IT",
    "MX",
    "NL",
    "SG",
    "ES",
    "TR",
    "AE",
    "GB",
    "JP"
];

const categories = [
    "aps",
    "alexa skills",
    "amazon devices",
    "warehouse deals",
    "mobile apps",
    "audible",
    "automotive",
    "baby",
    "beauty",
    "stripbooks",
    "fashion",
    "fashion womens",
    "fashion mens",
    "fashion girls",
    "fashion boys",
    "fashion baby",
    "electronics",
    "gift cards",
    "grocery",
    "handmade",
    "hpc",
    "kitchen",
    "industrial",
    "digital text",
    "fashion luggage",
    "luxury beauty",
    "dvd",
    "popular",
    "mi",
    "office products",
    "lawngarden",
    "pets",
    "instant video",
    "smart home",
    "software",
    "sporting",
    "specialty aps sns",
    "tools",
    "toys",
    "videogames"
]
module.exports = {
    availableCountries,
    categories
}